spring:
  application:
    name: api-gateway

  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
#            - Method= GET, POST
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://youtube.com
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Nishant
        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
