# We have commented below code as we have put this config to
# github https://github.com/officialnishantaggarwal/ecommerce-config-server

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
#
#resilience4j:
#  retry:
#    configs:
#      default:
#        maxRetryAttempts: 3
#        waitDuration: 100ms
#    instances:
#      inventoryRetry:
#        base-config: default
#        waitDuration: 200ms
#  ratelimiter:
#    instances:
#      inventoryRateLimiter:
#        limitRefreshPeriod: 5s
#        limitForPeriod: 1
#        timeoutDuration: 1s
#  circuitbreaker:
#    instances:
#      inventoryCircuitBreaker:
#        register-health-indicator: true #Expose circuit breaker health via actuator
#        sliding-window-size: 10 # Size of the sliding window for call recording
#        sliding-window-type: COUNT_BASED # Use count-based sliding window
#        minimum-number-of-calls: 10 # Minimum number of calls before calculating failure rate
#        failure-rate-threshold: 50 # if 50% (5 out of 10) calls fail, the circuit goes to open state
#        wait-duration-in-open-state: 20s # Time the circuit stays OPEN before moving to HALF_OPEN
#        permitted-number-of-calls-in-half-open-state: 3 # Number of test calls in HALF_OPEN state
#        event-consumer-buffer-size: 10 # Buffer size for event logs
#
